### ISSUE TITLE
Add return type to docblock for \Email\Email::forge

### ISSUE THREAD

**Issue by richard-myers** [fuel/email#21]
Could you please add the return type to the docblock for the forge function so we can get type hinting on the returned object.

``` php
/*
 * ...
 * @return  Email_Driver
 */
public static function forge($setup = null, array $config = array())
```

**Comment by frankdejonge** [comment]
Richard, I appreciate what you doing here, but you can easily send a pull request for this. Just saying "Fix this" does get a little annoying after a while. This can even be done in github in your fork, you don't even need to setup git on your local machine. There are also a lot of tutorials on how to send pull requests, fork, commit and all other stuff.
