### ISSUE TITLE
Proposal : Email attach_paths default

### ISSUE THREAD

**Issue by billmn** [fuel/email#24]
I think it can be useful that "attach_paths" in email config file use :

<pre>
// absolute path
'',

// fuelphp asset path
'__assets__',

// relative to docroot.
DOCROOT,
</pre>

So a user can attach a file, without add the default asset path ... 

<pre>$email->attach(\Asset::get_file('logo.gif', 'img'), true, 'cid:logo');</pre>

The config array key "assets" is only an example :)

**Comment by frankdejonge** [comment]
I can see where you're going with this, but that makes the email package coupled with the Asset class, which is way to big of a downer when you look at what 'problem' it's trying to solve. You can use the Asset class in your view, and let the package auto_include the file. That way you'll still have the advantage of using the Asset class, without the coupling. So I'll have to say no to this one.
