### ISSUE TITLE
You get a uninformative error if you try to auto-load your email config

### ISSUE THREAD

**Issue by fform** [fuel/email#27]
I added email as an always load package, and I put a local copy of the email config in my app path.

I assumed you'd need to always-load the email config manually in my config file, as some packages need that.

You get an error about merging arrays, which I assume has something to do with the config not wanting to load twice?

Solution: Either
A. Just ignore an already loaded email config
B. Make a note in the docs about not auto-loading it

Whatever the case, having some standardization of when you do and do not need to load a package config would be great

**Comment by frankdejonge** [comment]
What kind of error are you getting? The email config is loaded when you use the package, so no need for loading it manually. A note in the docs should be enough, no need to over engineer this.

**Comment by fform** [comment]
I agree, a simple note in the docs would suffice. Maybe a note about how to handle config loading for package creation too so it's all standardized. 

The error is a type error where it expects an array on ln 58 in packs/email/class/email.php

Thanks Frank

**Comment by WanWizard** [comment]
@FrenkyNet Is this note added? Can this issue be closed?

**Comment by frankdejonge** [comment]
Added it. Closing issue.
