### ISSUE TITLE
Problem with Email::header()

### ISSUE THREAD

**Issue by chrisveness** [fuel/email#39]
I think there is a bug with the array version of Email::header. The two-parameter version works fine, but the array version gets ignored.

Browsing the code, I suspect packages/email/classes/email/driver.php: in header(), the foreach uses $_header => $_value, but the following line uses $header / $value (line 455 in v1.5.3).

Chris

**Comment by WanWizard** [comment]
This problem has been fixed in 1.6/develop. 

I think it's save to upgrade your email package to 1.6/develop, or wait a few days, because 1.6 will be released soon.
