### ISSUE TITLE
Comma in the name will send 2 emails instead of 1

### ISSUE THREAD

**Issue by ghost** [fuel/email#46]
Hello there,
We have a detected a problem while setting the send to name in the email class that when having a comma in the name it sends out 2 emails instead of 1.
Please fix it. For now we are using a work around for it.
Thanks,

namespace Fuel\Tasks;

class Testmail {

```
public function run(){

    $email = \Email\Email::forge();
    /* @var $email \Email\Email_Driver */

    $email->from('noreply@email.com');

            $email->to('customer@business.com', 'firstname, lastname');   
            // this line will cause problems and send 2 emails

            $email->subject('testing comma name');
    $email->body('this is the body');
    $email->send();     
}
```

}

**Comment by frankdejonge** [comment]
@athares what driver are you using?

**Comment by frankdejonge** [comment]
@athares found out what was going wrong, thanks for spotting it :+1:

**Comment by ghost** [comment]
Thanks a lot sir.

Cheers,
