### ISSUE TITLE
Email::pipelining 503 Already authenticated

### ISSUE THREAD

**Issue by chrisveness** [fuel/email#50]
Using the Email::pipelining() function with SendGrid, Email_Driver_Smtp::smtp_authenticate() returns a 503 Already authenticated error status from SendGrid.

I managed to fix this by changing the 'use authentication' in Email_Driver_Smtp::__send() to

```
$authenticate = !empty($this->config['smtp']['username']) &&
                !empty($this->config['smtp']['password']) &&
                !($this->pipelining and !empty($this->smtp_connection));
```

**Comment by WanWizard** [comment]
I think checking the smtp_connection should be enough. If that is present, it should be in a usable state.
