### ISSUE TITLE
Issue with mailgun driver and string_attach in version 1.8

### ISSUE THREAD

**Issue by jihoun** [fuel/email#69]
attach works fine, but the way attach fills in the $attachments array seems to not be handled properly by the mailgun driver.

<img width="826" alt="screen shot 2016-08-25 at 09 11 08" src="https://cloud.githubusercontent.com/assets/14889507/17953219/1e9e6190-6aa4-11e6-83a9-30c664e3d961.png">

Here is the content of $this->attachments after the call to string_attach. So, indeed $file[0] is not defined.

```
(
    [inline] => Array
        (
        )

    [attachment] => Array
        (
            [cid:effc55b59e801141740f3d5c8f992ef6] => Array
                (
                    [file] => Array
                        (
                            [1] => Nicolas Lagier-1471824000.ics
                        )
                    [contents] => ...
                    [mime] => text/calendar
                    [disp] => attachment
                    [cid] => cid:effc55b59e801141740f3d5c8f992ef6
                )

        )

)
```

**Comment by WanWizard** [comment]
That is very weird, since https://github.com/fuel/email/blob/1.9/develop/classes/email/driver.php#L606 explicitly checks and creates it.

Is this by any chance an attachment created by `string_attach()`? Because due to the absense of a filename, that does not create the [0] index.

**Comment by WanWizard** [comment]
Oops, didn't read the title properly. Fix is on the way.
