### ISSUE TITLE
Don't attach https urls

### ISSUE THREAD

**Issue by felixkoch** [fuel/email#9]
In driver.php, Line 187:
    if (($beginning = substr($image_url, 0, 7)) !== 'http://' and $beginning !== 'htts://' and substr($image_url, 0, 4) !== 'cid:')
Should be:
    if (substr($image_url, 0, 7) !== 'http://' and substr($image_url, 0, 8) !== 'https://' and substr($image_url, 0, 4) !== 'cid:')

**Comment by felixkoch** [comment]
That is still wrong: 'https://' has 8 chars not 7. Use the code I suggested.

**Comment by frankdejonge** [comment]
This has already been fixed in a later commit. If you want to us to use your code. Send a pull request, don't say "Use this".

**Comment by felixkoch** [comment]
Sorry and Thank you.
